### ISSUE TITLE
REQUIRED process [config_parser-2] has died!

### ISSUE THREAD

**Issue by SharineLee** [ethz-asl/unreal_airsim#19]
i install UE4.24.3 and Airsim(you give)

when I run
roslaunch unreal_airsim parse_config_to_airsim.launch
shows
----
... logging to /home/sharine/.ros/log/88ee30f4-ad96-11eb-be6c-00d861bc2028/roslaunch-sharine-MS-7B98-2848.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sharine-MS-7B98:46001/

SUMMARY

PARAMETERS
 * /config_parser/config_file_path: /home/sharine/cod...
 * /config_parser/target_file_path: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    config_parser (unreal_airsim/parse_config_to_airsim.py)

auto-starting new master
process[master]: started with pid [2873]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 88ee30f4-ad96-11eb-be6c-00d861bc2028
process[rosout-1]: started with pid [2899]
started core service [/rosout]
process[config_parser-2]: started with pid [2902]
/home/sharine/Documents/AirSim/settings.json
[INFO] [1620214763.449762]: 
************************************************************************
* Starting config parser for unreal_airsim to AirSim config conversion *
************************************************************************
[INFO] [1620214763.459512]: Read source: '/home/sharine/code/unreal_airsim_ws/src/unreal_airsim/cfg/demo.yaml'
[INFO] [1620214763.463535]: Existing file '/home/sharine/Documents/AirSim/settings.json' was auto-generated and will be overwritten.
[INFO] [1620214763.466049]: Found camera 'Seg_cam'.
[INFO] [1620214763.469445]: Found imu 'Imu'.
[INFO] [1620214763.472197]: Found camera 'Scene_cam'.
[INFO] [1620214763.475673]: Found camera 'Depth_cam'.
[INFO] [1620214763.478462]: Found lidar 'Lidar'.
[INFO] [1620214763.482812]: Using vehicle name 'airsim_drone'.
[INFO] [1620214763.485061]: Wrote config to target file '/home/sharine/Documents/AirSim/settings.json'.
[INFO] [1620214763.486599]: 
******************************************************************
* Settings parsing finished successfully (0 Warnings, 0 Errors)! *
******************************************************************

REQUIRED process [config_parser-2] has died!
process has finished cleanly
log file: /home/sharine/.ros/log/88ee30f4-ad96-11eb-be6c-00d861bc2028/config_parser-2*.log
Initiating shutdown!

[config_parser-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

and UnrealEigene windows shows:
[2021.05.05-11.44.36:138][790]LogPlayLevel: Error: RunUAT ERROR: AutomationTool was unable to run successfully.

[2021.05.05-11.44.36:138][790]PackagingResults: Error: 启动失败！ Unknown Error

**Comment by Schmluk** [comment]
What exactly is the question? The config parser finishes as expected, all the logging below is from roslaunch shutting down after the parsing finished. Parsing the config does not affect UE4 (so all these notifications are unrelated). The config will be loaded the next time UE4 is started / loaded.

Hope this helps.

**Comment by SharineLee** [comment]
> What exactly is the question? The config parser finishes as expected, all the logging below is from roslaunch shutting down after the parsing finished. Parsing the config does not affect UE4 (so all these notifications are unrelated). The config will be loaded the next time UE4 is started / loaded.
> 
> Hope this helps.

**Comment by SharineLee** [comment]
> What exactly is the question? The config parser finishes as expected, all the logging below is from roslaunch shutting down after the parsing finished. Parsing the config does not affect UE4 (so all these notifications are unrelated). The config will be loaded the next time UE4 is started / loaded.
> 
> Hope this helps.

Thank you for your answer!

1. when i run: roslaunch unreal_airsim parse_config_to_airsim.launch
the terminal shows red words as shown below :

REQUIRED process [config_parser-2] has died!
process has finished cleanly
log file: /home/sharine/.ros/log/706998b8-adc1-11eb-be6c-00d861bc2028/config_parser-2*.log
Initiating shutdown!


2.  and the I open UE4 and open a block environment and click "Play"
shows a drone

3. Then, I run roslaunch unreal_airsim demo.launch
the terminal shows red words as shown below :

REQUIRED process [config_parser-2] has died!
process has finished cleanly
log file: /home/sharine/.ros/log/706998b8-adc1-11eb-be6c-00d861bc2028/config_parser-2*.log
Initiating shutdown!

**Comment by SharineLee** [comment]
The full information in terminal:

$ roslaunch unreal_airsim demo.launch
... logging to /home/sharine/.ros/log/a8de3fe8-ae0a-11eb-be6c-00d861bc2028/roslaunch-sharine-MS-7B98-31578.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sharine-MS-7B98:44077/

SUMMARY
========

PARAMETERS
 * /airsim_simulator/ClockSpeed: 1.0
 * /airsim_simulator/processors/RGBD_cam/color_camera_name: Scene_cam
 * /airsim_simulator/processors/RGBD_cam/depth_camera_name: Depth_cam
 * /airsim_simulator/processors/RGBD_cam/processor_type: DepthToPointcloud
 * /airsim_simulator/sensors/Depth_cam/CaptureSettings/FOV_Degrees: 90
 * /airsim_simulator/sensors/Depth_cam/CaptureSettings/Height: 480
 * /airsim_simulator/sensors/Depth_cam/CaptureSettings/Width: 640
 * /airsim_simulator/sensors/Depth_cam/T_B_S: [[1, 0, 0, 0.3], ...
 * /airsim_simulator/sensors/Depth_cam/image_type: DepthPlanner
 * /airsim_simulator/sensors/Depth_cam/pixels_as_float: True
 * /airsim_simulator/sensors/Depth_cam/rate: 3
 * /airsim_simulator/sensors/Depth_cam/sensor_type: Camera
 * /airsim_simulator/sensors/Imu/rate: 100
 * /airsim_simulator/sensors/Imu/sensor_type: Imu
 * /airsim_simulator/sensors/Lidar/NumberOfChannels: 16
 * /airsim_simulator/sensors/Lidar/PointsPerSecond: 100000
 * /airsim_simulator/sensors/Lidar/RotationsPerSecond: 10
 * /airsim_simulator/sensors/Lidar/T_B_S: [[0.8660254, 0.0,...
 * /airsim_simulator/sensors/Lidar/VerticalFOVLower: -30
 * /airsim_simulator/sensors/Lidar/VerticalFOVUpper: 30
 * /airsim_simulator/sensors/Lidar/rate: 3
 * /airsim_simulator/sensors/Lidar/sensor_type: Lidar
 * /airsim_simulator/sensors/Scene_cam/CaptureSettings/FOV_Degrees: 90
 * /airsim_simulator/sensors/Scene_cam/CaptureSettings/Height: 480
 * /airsim_simulator/sensors/Scene_cam/CaptureSettings/Width: 640
 * /airsim_simulator/sensors/Scene_cam/T_B_S: [[1, 0, 0, 0.3], ...
 * /airsim_simulator/sensors/Scene_cam/image_type: Scene
 * /airsim_simulator/sensors/Scene_cam/rate: 3
 * /airsim_simulator/sensors/Scene_cam/sensor_type: Camera
 * /airsim_simulator/sensors/Seg_cam/CaptureSettings/FOV_Degrees: 90
 * /airsim_simulator/sensors/Seg_cam/CaptureSettings/Height: 480
 * /airsim_simulator/sensors/Seg_cam/CaptureSettings/Width: 640
 * /airsim_simulator/sensors/Seg_cam/T_B_S: [[1, 0, 0, 0.3], ...
 * /airsim_simulator/sensors/Seg_cam/image_type: Segmentation
 * /airsim_simulator/sensors/Seg_cam/rate: 3
 * /airsim_simulator/sensors/Seg_cam/sensor_type: Camera
 * /airsim_simulator/state_refresh_rate: 100
 * /airsim_simulator/vehicle_name: airsim_drone
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /use_sim_time: True

NODES
  /
    airsim_simulator (unreal_airsim/airsim_simulator_node)
    rviz (rviz/rviz)
    tf_odom_to_world (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [31603]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to a8de3fe8-ae0a-11eb-be6c-00d861bc2028
process[rosout-1]: started with pid [31629]
started core service [/rosout]
process[tf_odom_to_world-2]: started with pid [31636]
process[airsim_simulator-3]: started with pid [31637]
process[rviz-4]: started with pid [31642]
I0506 09:30:37.925405 31637 simulator.cpp:49] Connected to the Airsim Server.
*** Aborted at 1620264637 (unix time) try "date -d @1620264637" if you are using GNU date ***
PC: @     0x7f23343fed9f _Unwind_Resume
*** SIGSEGV (@0x10) received by PID 31637 (TID 0x7f2335a0a240) from PID 16; stack trace: ***
    @     0x7f2335656899 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f23349a1980 (unknown)
    @     0x7f23343fed9f _Unwind_Resume
    @     0x7f2334e3c194 unreal_airsim::AirsimSimulator::startSimTimer()
    @     0x7f2334e47b7d unreal_airsim::AirsimSimulator::AirsimSimulator()
    @     0x55ccca13a2e8 (unknown)
    @     0x7f233401ebf7 __libc_start_main
    @     0x55ccca13a5aa (unknown)
================================================================================REQUIRED process [airsim_simulator-3] has died!
process has died [pid 31637, exit code -11, cmd /home/sharine/code/unreal_airsim_ws/devel/lib/unreal_airsim/airsim_simulator_node -alsologtostderr __name:=airsim_simulator __log:=/home/sharine/.ros/log/a8de3fe8-ae0a-11eb-be6c-00d861bc2028/airsim_simulator-3.log].
log file: /home/sharine/.ros/log/a8de3fe8-ae0a-11eb-be6c-00d861bc2028/airsim_simulator-3*.log
Initiating shutdown!
================================================================================
[rviz-4] killing on exit
[airsim_simulator-3] killing on exit
[tf_odom_to_world-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by SharineLee** [comment]
Is my UE's version not match? I use UE4.24.3.

**Comment by renezurbruegg** [comment]
I had similar issues as you did.
Are you using the fork of the Airsim plugin? ([https://github.com/ethz-asl/AirSim](https://github.com/ethz-asl/AirSim))

**Comment by SharineLee** [comment]
> I had similar issues as you do when using the wrong Airsim Plugin.
> Are you using the fork of the Airsim plugin? (https://github.com/ethz-asl/AirSim)

what's version UnrealEngine do you use? is UE4.24.3? or UE2.24.x?

**Comment by SharineLee** [comment]
> I had similar issues as you do when using the wrong Airsim Plugin.
> Are you using the fork of the Airsim plugin? (https://github.com/ethz-asl/AirSim)
yes, I use this fork of Airsim, but I use UnrealEngine4.24.3. I'm not sure the version of UnrealEngine is right.

this is my erro：
sharine@sharine-MS-7B98:~/unreal_airsim/UnrealSim_WS$ roslaunch unreal_airsim demo.launch 
... logging to /home/sharine/.ros/log/2be16e7e-b4a0-11eb-ae5c-00d861bc2028/roslaunch-sharine-MS-7B98-18264.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sharine-MS-7B98:36809/

SUMMARY
========

PARAMETERS
 * /airsim_simulator/ClockSpeed: 1.0
 * /airsim_simulator/processors/RGBD_cam/color_camera_name: Scene_cam
 * /airsim_simulator/processors/RGBD_cam/depth_camera_name: Depth_cam
 * /airsim_simulator/processors/RGBD_cam/processor_type: DepthToPointcloud
 * /airsim_simulator/sensors/Depth_cam/CaptureSettings/FOV_Degrees: 90
 * /airsim_simulator/sensors/Depth_cam/CaptureSettings/Height: 480
 * /airsim_simulator/sensors/Depth_cam/CaptureSettings/Width: 640
 * /airsim_simulator/sensors/Depth_cam/T_B_S: [[1, 0, 0, 0.3], ...
 * /airsim_simulator/sensors/Depth_cam/image_type: DepthPlanner
 * /airsim_simulator/sensors/Depth_cam/pixels_as_float: True
 * /airsim_simulator/sensors/Depth_cam/rate: 3
 * /airsim_simulator/sensors/Depth_cam/sensor_type: Camera
 * /airsim_simulator/sensors/Imu/rate: 100
 * /airsim_simulator/sensors/Imu/sensor_type: Imu
 * /airsim_simulator/sensors/Lidar/NumberOfChannels: 16
 * /airsim_simulator/sensors/Lidar/PointsPerSecond: 100000
 * /airsim_simulator/sensors/Lidar/RotationsPerSecond: 10
 * /airsim_simulator/sensors/Lidar/T_B_S: [[0.8660254, 0.0,...
 * /airsim_simulator/sensors/Lidar/VerticalFOVLower: -30
 * /airsim_simulator/sensors/Lidar/VerticalFOVUpper: 30
 * /airsim_simulator/sensors/Lidar/rate: 3
 * /airsim_simulator/sensors/Lidar/sensor_type: Lidar
 * /airsim_simulator/sensors/Scene_cam/CaptureSettings/FOV_Degrees: 90
 * /airsim_simulator/sensors/Scene_cam/CaptureSettings/Height: 480
 * /airsim_simulator/sensors/Scene_cam/CaptureSettings/Width: 640
 * /airsim_simulator/sensors/Scene_cam/T_B_S: [[1, 0, 0, 0.3], ...
 * /airsim_simulator/sensors/Scene_cam/image_type: Scene
 * /airsim_simulator/sensors/Scene_cam/rate: 3
 * /airsim_simulator/sensors/Scene_cam/sensor_type: Camera
 * /airsim_simulator/sensors/Seg_cam/CaptureSettings/FOV_Degrees: 90
 * /airsim_simulator/sensors/Seg_cam/CaptureSettings/Height: 480
 * /airsim_simulator/sensors/Seg_cam/CaptureSettings/Width: 640
 * /airsim_simulator/sensors/Seg_cam/T_B_S: [[1, 0, 0, 0.3], ...
 * /airsim_simulator/sensors/Seg_cam/image_type: Segmentation
 * /airsim_simulator/sensors/Seg_cam/rate: 3
 * /airsim_simulator/sensors/Seg_cam/sensor_type: Camera
 * /airsim_simulator/state_refresh_rate: 100
 * /airsim_simulator/vehicle_name: airsim_drone
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /use_sim_time: True

NODES
  /
    airsim_simulator (unreal_airsim/airsim_simulator_node)
    rviz (rviz/rviz)
    tf_odom_to_world (tf/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[tf_odom_to_world-1]: started with pid [18294]
process[airsim_simulator-2]: started with pid [18295]
process[rviz-3]: started with pid [18300]
I0514 18:36:11.782753 18295 simulator.cpp:49] Connected to the Airsim Server.
*** Aborted at 1620988571 (unix time) try "date -d @1620988571" if you are using GNU date ***
PC: @     0x7f6b01250d9f _Unwind_Resume
*** SIGSEGV (@0x10) received by PID 18295 (TID 0x7f6b025ec200) from PID 16; stack trace: ***
    @     0x7f6b02239899 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f6b017f3980 (unknown)
    @     0x7f6b01250d9f _Unwind_Resume
    @     0x7f6b01a1f194 unreal_airsim::AirsimSimulator::startSimTimer()
    @     0x7f6b01a2ab7d unreal_airsim::AirsimSimulator::AirsimSimulator()
    @     0x55b09a5c4978 (unknown)
    @     0x7f6b00e70bf7 __libc_start_main
    @     0x55b09a5c4dea (unknown)
==========REQUIRED process [airsim_simulator-2] has died!
process has died [pid 18295, exit code -11, cmd /home/sharine/unreal_airsim/UnrealSim_WS/devel/lib/unreal_airsim/airsim_simulator_node -alsologtostderr __name:=airsim_simulator __log:=/home/sharine/.ros/log/2be16e7e-b4a0-11eb-ae5c-00d861bc2028/airsim_simulator-2.log].
log file: /home/sharine/.ros/log/2be16e7e-b4a0-11eb-ae5c-00d861bc2028/airsim_simulator-2*.log
Initiating shutdown!==================================
[rviz-3] killing on exit
[airsim_simulator-2] killing on exit
[tf_odom_to_world-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by renezurbruegg** [comment]
I think had it running on UE 4.24.3. 
What gcc version do you use? I had troubles when compiling with gcc 8/9, compiling with gcc 7 fixed some issues.

If the error persists, depending on what ROS features you need, you might consider upgrading to UE 4.25 and using Airsim v1.4.0 [This branch](https://github.com/ethz-asl/AirSim/tree/v1.4.0/rospackage). It should contain a working ros package.

**Comment by SharineLee** [comment]
yes, the error still persists. I am considering use UE4.25 and Airsim v1.4.0 now.

Could glocal_exploration [https://github.com/ethz-asl/glocal_exploration](url) run with ros package in UE4.25 and Airsim v1.4.0?

**Comment by Schmluk** [comment]
Dear Sharine,

The shutdown after the config parsing is expected, once the parsing finishes successfully the node exits and the launch file terminates (since the parser is required).

Unfortunately there are known issues with varying versions of UE4 and AirSim, since some features changed and the AirSim support (especially for linux-based systems) is sometimes not that thorough. We developed the pipeline for our fork of AirSim and UE 4.24.3. 

glocal_exploration can be run with any simulator, but we recommend unreal_airsim since it features realistic odometry drift patterns. unreal_airsim should also work for more recent versions of UE4+AirSim but we haven't tested that.

**Comment by SharineLee** [comment]
> Dear Sharine,
> 
> The shutdown after the config parsing is expected, once the parsing finishes successfully the node exits and the launch file terminates (since the parser is required).
> 
> Unfortunately there are known issues with varying versions of UE4 and AirSim, since some features changed and the AirSim support (especially for linux-based systems) is sometimes not that thorough. We developed the pipeline for our fork of AirSim and UE 4.24.3.
> 
> glocal_exploration can be run with any simulator, but we recommend unreal_airsim since it features realistic odometry drift patterns. unreal_airsim should also work for more recent versions of UE4+AirSim but we haven't tested that.

Dear Schmluk ,

Thank you for your kind reply. 

Since I can’t use UE4.24.3 and Airsim1.2.2, but I can successfully use the ros package of UE4.25.4+Airsim1.4，so I plan to run a open-source visual-imu odometer (such as vinsmono, etc.) with airsim, and then add Gaussian noise to the pictures and imu data. Finally, I maybe able give this odometer ‘s drift to glocal_exploration without unreal_airsim.

Thanks a lot.

**Comment by Schmluk** [comment]
Hi @SharineLee 
Just to let you know we updated our simulator to work with the latest version of AirSim and UE4.25, available in the current master branch!

**Comment by yonggaogit** [comment]
> I had similar issues as you do when using the wrong Airsim Plugin. Are you using the fork of the Airsim plugin? (https://github.com/ethz-asl/AirSim)

Did you fix this problem?

**Comment by yonggaogit** [comment]
> i install UE4.24.3 and Airsim(you give)
> ## when I run
> roslaunch unreal_airsim parse_config_to_airsim.launch
> shows
> 
> ... logging to /home/sharine/.ros/log/88ee30f4-ad96-11eb-be6c-00d861bc2028/roslaunch-sharine-MS-7B98-2848.log Checking log directory for disk usage. This may take a while. Press Ctrl-C to interrupt Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://sharine-MS-7B98:46001/
> 
> SUMMARY
> 
> PARAMETERS
> 
>     * /config_parser/config_file_path: /home/sharine/cod...
> 
>     * /config_parser/target_file_path:
> 
>     * /rosdistro: melodic
> 
>     * /rosversion: 1.14.10
> 
> 
> NODES / config_parser (unreal_airsim/parse_config_to_airsim.py)
> 
> auto-starting new master process[master]: started with pid [2873] ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 88ee30f4-ad96-11eb-be6c-00d861bc2028 process[rosout-1]: started with pid [2899] started core service [/rosout] process[config_parser-2]: started with pid [2902] /home/sharine/Documents/AirSim/settings.json [INFO] [1620214763.449762]:
> 
>     * Starting config parser for unreal_airsim to AirSim config conversion *
> 
> 
> [INFO] [1620214763.459512]: Read source: '/home/sharine/code/unreal_airsim_ws/src/unreal_airsim/cfg/demo.yaml' [INFO] [1620214763.463535]: Existing file '/home/sharine/Documents/AirSim/settings.json' was auto-generated and will be overwritten. [INFO] [1620214763.466049]: Found camera 'Seg_cam'. [INFO] [1620214763.469445]: Found imu 'Imu'. [INFO] [1620214763.472197]: Found camera 'Scene_cam'. [INFO] [1620214763.475673]: Found camera 'Depth_cam'. [INFO] [1620214763.478462]: Found lidar 'Lidar'. [INFO] [1620214763.482812]: Using vehicle name 'airsim_drone'. [INFO] [1620214763.485061]: Wrote config to target file '/home/sharine/Documents/AirSim/settings.json'. [INFO] [1620214763.486599]:
> 
>     * Settings parsing finished successfully (0 Warnings, 0 Errors)! *
> 
> 
> REQUIRED process [config_parser-2] has died! process has finished cleanly log file: /home/sharine/.ros/log/88ee30f4-ad96-11eb-be6c-00d861bc2028/config_parser-2*.log Initiating shutdown!
> 
> [config_parser-2] killing on exit [rosout-1] killing on exit [master] killing on exit shutting down processing monitor... ... shutting down processing monitor complete done
> 
> and UnrealEigene windows shows: [2021.05.05-11.44.36:138][790]LogPlayLevel: Error: RunUAT ERROR: AutomationTool was unable to run successfully.
> 
> [2021.05.05-11.44.36:138][790]PackagingResults: Error: 启动失败！ Unknown Error

How did you solve this problem in the end? I modified the version according to your description and the problem still exists.

**Comment by yonggaogit** [comment]
> 

How did you solve this problem in the end? I modified the version according to your description and the problem still exists.

**Comment by yonggaogit** [comment]
> > I had similar issues as you do when using the wrong Airsim Plugin.
> > Are you using the fork of the Airsim plugin? (https://github.com/ethz-asl/AirSim)
> > yes, I use this fork of Airsim, but I use UnrealEngine4.24.3. I'm not sure the version of UnrealEngine is right.
> 
> this is my erro： sharine@sharine-MS-7B98:~/unreal_airsim/UnrealSim_WS$ roslaunch unreal_airsim demo.launch ... logging to /home/sharine/.ros/log/2be16e7e-b4a0-11eb-ae5c-00d861bc2028/roslaunch-sharine-MS-7B98-18264.log Checking log directory for disk usage. This may take a while. Press Ctrl-C to interrupt Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://sharine-MS-7B98:36809/
> # SUMMARY
> 
> PARAMETERS
> 
>     * /airsim_simulator/ClockSpeed: 1.0
> 
>     * /airsim_simulator/processors/RGBD_cam/color_camera_name: Scene_cam
> 
>     * /airsim_simulator/processors/RGBD_cam/depth_camera_name: Depth_cam
> 
>     * /airsim_simulator/processors/RGBD_cam/processor_type: DepthToPointcloud
> 
>     * /airsim_simulator/sensors/Depth_cam/CaptureSettings/FOV_Degrees: 90
> 
>     * /airsim_simulator/sensors/Depth_cam/CaptureSettings/Height: 480
> 
>     * /airsim_simulator/sensors/Depth_cam/CaptureSettings/Width: 640
> 
>     * /airsim_simulator/sensors/Depth_cam/T_B_S: [[1, 0, 0, 0.3], ...
> 
>     * /airsim_simulator/sensors/Depth_cam/image_type: DepthPlanner
> 
>     * /airsim_simulator/sensors/Depth_cam/pixels_as_float: True
> 
>     * /airsim_simulator/sensors/Depth_cam/rate: 3
> 
>     * /airsim_simulator/sensors/Depth_cam/sensor_type: Camera
> 
>     * /airsim_simulator/sensors/Imu/rate: 100
> 
>     * /airsim_simulator/sensors/Imu/sensor_type: Imu
> 
>     * /airsim_simulator/sensors/Lidar/NumberOfChannels: 16
> 
>     * /airsim_simulator/sensors/Lidar/PointsPerSecond: 100000
> 
>     * /airsim_simulator/sensors/Lidar/RotationsPerSecond: 10
> 
>     * /airsim_simulator/sensors/Lidar/T_B_S: [[0.8660254, 0.0,...
> 
>     * /airsim_simulator/sensors/Lidar/VerticalFOVLower: -30
> 
>     * /airsim_simulator/sensors/Lidar/VerticalFOVUpper: 30
> 
>     * /airsim_simulator/sensors/Lidar/rate: 3
> 
>     * /airsim_simulator/sensors/Lidar/sensor_type: Lidar
> 
>     * /airsim_simulator/sensors/Scene_cam/CaptureSettings/FOV_Degrees: 90
> 
>     * /airsim_simulator/sensors/Scene_cam/CaptureSettings/Height: 480
> 
>     * /airsim_simulator/sensors/Scene_cam/CaptureSettings/Width: 640
> 
>     * /airsim_simulator/sensors/Scene_cam/T_B_S: [[1, 0, 0, 0.3], ...
> 
>     * /airsim_simulator/sensors/Scene_cam/image_type: Scene
> 
>     * /airsim_simulator/sensors/Scene_cam/rate: 3
> 
>     * /airsim_simulator/sensors/Scene_cam/sensor_type: Camera
> 
>     * /airsim_simulator/sensors/Seg_cam/CaptureSettings/FOV_Degrees: 90
> 
>     * /airsim_simulator/sensors/Seg_cam/CaptureSettings/Height: 480
> 
>     * /airsim_simulator/sensors/Seg_cam/CaptureSettings/Width: 640
> 
>     * /airsim_simulator/sensors/Seg_cam/T_B_S: [[1, 0, 0, 0.3], ...
> 
>     * /airsim_simulator/sensors/Seg_cam/image_type: Segmentation
> 
>     * /airsim_simulator/sensors/Seg_cam/rate: 3
> 
>     * /airsim_simulator/sensors/Seg_cam/sensor_type: Camera
> 
>     * /airsim_simulator/state_refresh_rate: 100
> 
>     * /airsim_simulator/vehicle_name: airsim_drone
> 
>     * /rosdistro: melodic
> 
>     * /rosversion: 1.14.10
> 
>     * /use_sim_time: True
> 
> 
> NODES / airsim_simulator (unreal_airsim/airsim_simulator_node) rviz (rviz/rviz) tf_odom_to_world (tf/static_transform_publisher)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[tf_odom_to_world-1]: started with pid [18294] process[airsim_simulator-2]: started with pid [18295] process[rviz-3]: started with pid [18300] I0514 18:36:11.782753 18295 simulator.cpp:49] Connected to the Airsim Server. *** Aborted at 1620988571 (unix time) try "date -d @1620988571" if you are using GNU date *** PC: @ 0x7f6b01250d9f _Unwind_Resume *** SIGSEGV (@0x10) received by PID 18295 (TID 0x7f6b025ec200) from PID 16; stack trace: *** @ 0x7f6b02239899 google::(anonymous namespace)::FailureSignalHandler() @ 0x7f6b017f3980 (unknown) @ 0x7f6b01250d9f _Unwind_Resume @ 0x7f6b01a1f194 unreal_airsim::AirsimSimulator::startSimTimer() @ 0x7f6b01a2ab7d unreal_airsim::AirsimSimulator::AirsimSimulator() @ 0x55b09a5c4978 (unknown) @ 0x7f6b00e70bf7 __libc_start_main @ 0x55b09a5c4dea (unknown) ==========REQUIRED process [airsim_simulator-2] has died! process has died [pid 18295, exit code -11, cmd /home/sharine/unreal_airsim/UnrealSim_WS/devel/lib/unreal_airsim/airsim_simulator_node -alsologtostderr __name:=airsim_simulator __log:=/home/sharine/.ros/log/2be16e7e-b4a0-11eb-ae5c-00d861bc2028/airsim_simulator-2.log]. log file: /home/sharine/.ros/log/2be16e7e-b4a0-11eb-ae5c-00d861bc2028/airsim_simulator-2*.log Initiating shutdown!================================== [rviz-3] killing on exit [airsim_simulator-2] killing on exit [tf_odom_to_world-1] killing on exit shutting down processing monitor... ... shutting down processing monitor complete done

How did you solve this problem in the end? I modified the version according to your description and the problem still exists.
