### ISSUE TITLE
LowLevelFatalError about Vulkan

### ISSUE THREAD

**Issue by valenbase** [ethz-asl/unreal_airsim#21]
Error details:

4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.

LowLevelFatalError [File:Unknown] [Line: 772]

VulkanRHI::vkQueueSubmit(Queue, 1, &SubmitInfo, Fence->GetHandle()) failed, VkResult=-4
at /home/xxxx/UnrealEngine_4.24/Engine/Source/Runtime/VulkanRHI/Private/VulkanQueue.cpp:71
with error VK_ERROR_DEVICE_LOST

Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119
Malloc Size=124960 LargeMemoryPoolOffset=256096
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.

**Comment by Schmluk** [comment]
Hi @valenbase

Apologies for seeing your issue this late, somehow no notification was sent. There is a known issue within Vulkan (not sure if fixed in current releases), where, in particular on low graphics memory machines, Vulkan does not check how much memory is available and simply segfaults when trying to read/write out of physical memory. The easiest fix is to run on OpenGL i.e. uncomment TargetedRHIs=GLSL_430 in Engine/Config/BaseEngine.ini.

Otherwise make sure your Vulkan installation is up to date and running.

**Comment by valenbase** [comment]
> Hi @valenbase
> 
> Apologies for seeing your issue this late, somehow no notification was sent. There is a known issue within Vulkan (not sure if fixed in current releases), where, in particular on low graphics memory machines, Vulkan does not check how much memory is available and simply segfaults when trying to read/write out of physical memory. The easiest fix is to run on OpenGL i.e. uncomment TargetedRHIs=GLSL_430 in Engine/Config/BaseEngine.ini.
> 
> Otherwise make sure your Vulkan installation is up to date and running.

hi @Schmluk , sorry for the late reply, I use a new machine and fixed it, thanks!!!

**Comment by HongLouyemeng** [comment]
> Hi @valenbase
> 
> Apologies for seeing your issue this late, somehow no notification was sent. There is a known issue within Vulkan (not sure if fixed in current releases), where, in particular on low graphics memory machines, Vulkan does not check how much memory is available and simply segfaults when trying to read/write out of physical memory. The easiest fix is to run on OpenGL i.e. uncomment TargetedRHIs=GLSL_430 in Engine/Config/BaseEngine.ini.
> 
> Otherwise make sure your Vulkan installation is up to date and running.

My  Mac graphics processor does not support opengl4  in Vmware Funsion Ubuntu18.04

**Comment by KirillMouraviev** [comment]
I uncommented line `TargetedRHIs=GLSL_430` and commented line `TargetedRHIs=SF_VULKAN_SM5` in `Engine/Config/BaseEngine.ini` file. I launched the binary and got the following message:
![Снимок экрана от 2022-06-17 11-23-50](https://user-images.githubusercontent.com/15195368/174258503-df023747-b28c-4c28-bd38-2fb4ee42409e.png)

Where can I find cooked content for OpenGL?

**Comment by HongLouyemeng** [comment]
> I uncommented line `TargetedRHIs=GLSL_430` and commented line `TargetedRHIs=SF_VULKAN_SM5` in `Engine/Config/BaseEngine.ini` file. I launched the binary and got the following message: ![Снимок экрана от 2022-06-17 11-23-50](https://user-images.githubusercontent.com/15195368/174258503-df023747-b28c-4c28-bd38-2fb4ee42409e.png)
> 
> Where can I find cooked content for OpenGL?

Sorry, I have skipped using the simulator to debug code, so I do not continue to study this issue,Good luck!
