### ISSUE TITLE
REQUIRED process [config_parser-2] has died!

### ISSUE THREAD

**Issue by sz990707** [ethz-asl/unreal_airsim#25]
Dear Schmluk,
          When i roslaunch unreal_airsim parse_config_to_airsim.launch.  the REQUIRED process [config_parser-2] has died!
i see you say "The shutdown after the config parsing is expected, once the parsing finishes successfully the node exits and the launch file terminates (since the parser is required)." AS a chinese beginner,I don't know or realize what is parser.could you tell  me where can download the parser or other way to solve this problem,thank you very much!

**Comment by Schmluk** [comment]
Dear @sz990707,

Could you append the console output? The parser is the node that is being executed. As long as it says 'Finished successfully' before shutting down everything went right. The other messages are the tear down of the ROS environment.

**Comment by yonggaogit** [comment]
> 

Dear Schmluk, I had the same problem. The console output as shown below
`SUMMARY
========

PARAMETERS
 * /config_parser/config_file_path: /home/gao/project...
 * /config_parser/target_file_path: 
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    config_parser (unreal_airsim/parse_config_to_airsim.py)

auto-starting new master
process[master]: started with pid [25674]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e4e67816-21fe-11ed-99d5-f37f88cb2673
process[rosout-1]: started with pid [25691]
started core service [/rosout]
process[config_parser-2]: started with pid [25694]
[INFO] [1661161417.104791]: 
************************************************************************
* Starting config parser for unreal_airsim to AirSim config conversion *
************************************************************************
[INFO] [1661161417.112706]: Read source: '/home/gao/project/unreal_airsim_ws/src/unreal_airsim/cfg/demo.yaml'
[INFO] [1661161417.113399]: No existing '/home/gao/Documents/AirSim/settings.json' found.
[INFO] [1661161417.114099]: Found camera 'Scene_cam'.
[INFO] [1661161417.159594]: Found camera 'Depth_cam'.
[INFO] [1661161417.160514]: Found camera 'Seg_cam'.
[INFO] [1661161417.161318]: Found lidar 'Lidar'.
[INFO] [1661161417.162098]: Found imu 'Imu'.
[INFO] [1661161417.163265]: Using vehicle name 'airsim_drone'.
[INFO] [1661161417.164153]: Wrote config to target file '/home/gao/Documents/AirSim/settings.json'.
[INFO] [1661161417.164858]: 
******************************************************************
* Settings parsing finished successfully (0 Warnings, 0 Errors)! *
******************************************************************
[INFO] [1661161417.165561]: This process will now terminate. This is intended behavior.
================================================================================REQUIRED process [config_parser-2] has died!
process has finished cleanly
log file: /home/gao/.ros/log/e4e67816-21fe-11ed-99d5-f37f88cb2673/config_parser-2*.log
Initiating shutdown!
================================================================================
[config_parser-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
`

**Comment by Schmluk** [comment]
Hi @yonggaogit 

This is intended behavior. 
>```
>******************************************************************
>* Settings parsing finished successfully (0 Warnings, 0 Errors)! *
>******************************************************************
>[INFO] [1661161417.165561]: This process will now terminate. This is intended behavior.
>```

What you see is the ROS launch environment tearing down after finishing execution.
